package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SIGNAL extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SIGNAL() {
    super(0xfdef8274844e4810L, 0xbe06dd00182a0144L, 0x68cbc40979b00c51L, "SIGNAL", "r:6ca5d6a8-eabb-4366-950a-7442a0e145fd(ArduinoML.structure)/7551344745192098897");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "high", 0x68cbc40979b00c52L, "r:6ca5d6a8-eabb-4366-950a-7442a0e145fd(ArduinoML.structure)/7551344745192098898");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "low", 0x68cbc40979b00c53L, "r:6ca5d6a8-eabb-4366-950a-7442a0e145fd(ArduinoML.structure)/7551344745192098899");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xfdef8274844e4810L, 0xbe06dd00182a0144L, 0x68cbc40979b00c51L, 0x68cbc40979b00c52L, 0x68cbc40979b00c53L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_HIGH_0, myMember_LOW_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_HIGH_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HIGH":
        return myMember_HIGH_0;
      case "LOW":
        return myMember_LOW_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
